Repository onosproject/onos-test, pull requests merged in 2019-09, with the labels that each got.

#100 Wait for updates to complete on 'onit set image'
  pkg/onit/cli/set.go
  pkg/onit/console/status.go
  pkg/onit/k8s/app.go
  pkg/onit/k8s/image.go
  pkg/onit/k8s/network.go
  pkg/onit/k8s/onos-cli.go
  pkg/onit/k8s/onos-config.go
  pkg/onit/k8s/onos-topo.go
  pkg/onit/k8s/simulator.go
Labels: enhancement

#99 Update device tests to avoid new error checking
  test/topo/cli.go
  test/topo/device.go
Labels: bug

#103 Add resource label to onos-gui deployment and service
  pkg/onit/k8s/gui.go
Labels: bug

#104 Change Raft protocol configuration import to use atomix-api dependency
  go.mod
  go.sum
  pkg/onit/k8s/partitions.go
  test/env/env.go
  test/integration/transactiontest.go
Labels: bug

#109 Updated documents for Microk8s and onos-gui
  docs/run.md
  docs/setup.md
Labels: documentation

#111 Updated docs for running GUI on KinD
  docs/run.md
  docs/setup.md
Labels: enhancement

#108 Fix remove network command to find correct configmaps based on given …
  pkg/onit/k8s/cluster.go
Labels: bug
