Repository onosproject/onos-test, pull requests merged in 2019-11, with the labels that each got.

#141 Add kubetest tool for generic Kubernetes testing
  Makefile
  build/onos-test-runner/Dockerfile
  build/onos-tests/Dockerfile
  cmd/kubetest/main.go
  cmd/onos-tests/main.go
  go.mod
  go.sum
  pkg/kubetest/benchmark.go
  pkg/kubetest/cli.go
  pkg/kubetest/config.go
  pkg/kubetest/coordinator.go
  pkg/kubetest/executor.go
  pkg/kubetest/job.go
  pkg/kubetest/logging.go
  pkg/kubetest/registry.go
  pkg/kubetest/runner.go
  pkg/kubetest/test.go
  pkg/kubetest/worker.go
  pkg/util/k8s/k8s.go
  test/kubetest/suites.go
Labels: WIP

#146 Removing traces of rollback update
  test/integration/transactiontest.go
Labels: enhancement

#150 Removed loading of old JSON stores
  pkg/onit/k8s/onos-config.go
Labels: enhancement

#151 Removing broken mount of old /etc/onos-config/configs
  pkg/onit/k8s/onos-config.go
Labels: bug
