Repository onosproject/onos-test, pull requests merged in 2019-12, with the labels that each got.

#166 Fix linter errors
  benchmark/grpc/grpc_bench.go
  benchmark/nopaxos/map.go
  cmd/grpc-test/main.go
  cmd/onos-benchmarks/main.go
  pkg/benchmark/benchmark.go
  pkg/benchmark/cluster.go
  pkg/benchmark/executor.go
  pkg/benchmark/job.go
  pkg/benchmark/registry.go
  pkg/benchmark/worker.go
  pkg/onit/cli/add.go
  pkg/onit/cli/get.go
  pkg/onit/cli/services.go
  pkg/onit/cli/test.go
  pkg/onit/cluster/cluster.go
  pkg/onit/cluster/service.go
  pkg/test/cluster.go
  pkg/test/coordinator.go
  pkg/test/executor.go
  pkg/test/job.go
  pkg/test/registry.go
Labels: bug

#167 Fix bugs in create cluster command
  pkg/onit/cli/create.go
  pkg/onit/cluster/service.go
Labels: bug

#165 Fix race condition where value is loaded before the device state is complete
  test/config/singlestatetest.go
Labels: bug

#172 Avoid non-zero exit codes when tests succeed
  pkg/benchmark/coordinator.go
  pkg/cluster/runner.go
  pkg/test/coordinator.go
Labels: bug

#173 Replace script name with 'onit' when running command job
  pkg/onit/cli/job.go
Labels: bug

#174 Fix various benchmark bugs
  pkg/benchmark/config.go
  pkg/benchmark/coordinator.go
  pkg/cluster/cluster.go
  pkg/kube/kubeapi.go
  pkg/test/config.go
  pkg/test/coordinator.go
Labels: bug

#176 Ensure benchmarks can deploy and manage multiple workers
  benchmark/grpc/grpc_bench.go
  benchmark/nopaxos/map.go
  pkg/benchmark/benchmark.go
  pkg/benchmark/benchmark.pb.go
  pkg/benchmark/benchmark.proto
  pkg/benchmark/config.go
  pkg/benchmark/coordinator.go
  pkg/benchmark/worker.go
  pkg/onit/cli/benchmark.go
  pkg/onit/cli/test.go
Labels: bug

#179 Updated onit docs with some minor corrections and examples
  docs/getting-started.md
  docs/overview.md
  docs/testing.md
Labels: documentation

#182 change order of jobs in onos-tests to build docs before integration t…
  .travis.yml
Labels: enhancement

#186 Add failure thresholds to readiness probes to avoid unnecessary restarts
  pkg/onit/cluster/atomix.go
  pkg/onit/cluster/network.go
  pkg/onit/cluster/service.go
  pkg/onit/cluster/simulator.go
  pkg/test/coordinator.go
Labels: bug

#185 Add a script to run integration tests
  .travis.yml
  build/bin/run-integration-tests
Labels: DO_NOT_MERGE

#195 Update makefile to remove integration test target
  Makefile
Labels: enhancement

#190 Auto generate onit cli markdown files
  Makefile
  cmd/onit-cli-docs-gen/main.go
  docs/cli/onit.md
  docs/cli/onit_add.md
  docs/cli/onit_add_app.md
  docs/cli/onit_add_network.md
  docs/cli/onit_add_simulator.md
  docs/cli/onit_benchmark.md
  docs/cli/onit_completion.md
  docs/cli/onit_create.md
  docs/cli/onit_create_cluster.md
  docs/cli/onit_delete.md
  docs/cli/onit_delete_cluster.md
  docs/cli/onit_exec.md
  docs/cli/onit_get.md
  docs/cli/onit_get_apps.md
  docs/cli/onit_get_clusters.md
  docs/cli/onit_get_networks.md
  docs/cli/onit_get_simulators.md
  docs/cli/onit_remove.md
  docs/cli/onit_remove_app.md
  docs/cli/onit_remove_network.md
  docs/cli/onit_remove_simulator.md
  docs/cli/onit_test.md
  go.sum
  pkg/onit/cli/root.go
Labels: documentation

#193 Fix and update onos-test docs
  docs/cli/onit.md
  docs/cli/onit_add.md
  docs/cli/onit_add_app.md
  docs/cli/onit_add_network.md
  docs/cli/onit_add_simulator.md
  docs/cli/onit_benchmark.md
  docs/cli/onit_completion.md
  docs/cli/onit_create.md
  docs/cli/onit_create_cluster.md
  docs/cli/onit_delete.md
  docs/cli/onit_delete_cluster.md
  docs/cli/onit_exec.md
  docs/cli/onit_get.md
  docs/cli/onit_get_apps.md
  docs/cli/onit_get_clusters.md
  docs/cli/onit_get_networks.md
  docs/cli/onit_get_simulators.md
  docs/cli/onit_remove.md
  docs/cli/onit_remove_app.md
  docs/cli/onit_remove_network.md
  docs/cli/onit_remove_simulator.md
  docs/cli/onit_test.md
  docs/debugging.md
  docs/getting-started.md
  docs/overview.md
  pkg/onit/cli/add.go
  pkg/onit/cli/create.go
  pkg/onit/cli/delete.go
  pkg/onit/cli/remove.go
Labels: documentation

#192 Minimize service, deployment, node arguments passed to their constructors
  pkg/onit/cluster/app.go
  pkg/onit/cluster/atomix.go
  pkg/onit/cluster/cli.go
  pkg/onit/cluster/config.go
  pkg/onit/cluster/deployment.go
  pkg/onit/cluster/network.go
  pkg/onit/cluster/node.go
  pkg/onit/cluster/partition.go
  pkg/onit/cluster/service.go
  pkg/onit/cluster/simulator.go
  pkg/onit/cluster/topo.go
Labels: enhancement

#189 Fix delete, wait to make sure all of the deployments have been removed
  pkg/cluster/cluster.go
Labels: enhancement

#198 Added a section about how to run GUI on onit
  docs/debugging.md
Labels: documentation

#199 Expose API for not registering a simulator with onos-topo
  pkg/onit/cluster/simulator.go
  pkg/onit/env/simulator.go
Labels: enhancement

#200 Fix incorrect getStatus timeout in test coordinator
  pkg/test/coordinator.go
Labels: bug
