Repository onosproject/onos-test, pull requests merged in 2019-08, with the labels that each got.

#16 Support --docker-registry option
  pkg/cli/cli.go
  pkg/runner/cluster.go
  pkg/runner/config.go
  pkg/runner/network.go
  pkg/runner/onos-config.go
  pkg/runner/onos-topo.go
  pkg/runner/simulator.go
  pkg/runner/test.go
Labels: enhancement

#22 Rename OnitController to pass linter test
  pkg/onit/controller.go
Labels: enhancement

#31 Initialize onit configuration lazily
  pkg/onit/cli/config.go
Labels: bug

#35 Fail reading configuration file on errors other than ConfigFileNotFoundError
  pkg/onit/cli/config.go
Labels: bug

#25 More thorough onit command documentation
  go.mod
  go.sum
  pkg/onit/cli/add.go
  pkg/onit/cli/cli.go
  pkg/onit/cli/create.go
  pkg/onit/cli/debug.go
  pkg/onit/cli/delete.go
  pkg/onit/cli/fetch.go
  pkg/onit/cli/get.go
  pkg/onit/cli/remove.go
  pkg/onit/cli/run.go
  pkg/onit/cli/set.go
Labels: documentation

#36 Remove dependency on k8s templating to avoid dependency conflicts
  go.mod
  pkg/onit/cli/add.go
  pkg/onit/cli/cli.go
  pkg/onit/cli/create.go
  pkg/onit/cli/debug.go
  pkg/onit/cli/delete.go
  pkg/onit/cli/fetch.go
  pkg/onit/cli/get.go
  pkg/onit/cli/remove.go
  pkg/onit/cli/run.go
  pkg/onit/cli/set.go
Labels: bug

#32 give a name (itests) to the cluster for integration tests
  Makefile
Labels: enhancement

#40 Support Kubernetes operations inside tests
  go.mod
  go.sum
  pkg/onit/atomix.go
  pkg/onit/cluster.go
  pkg/onit/test.go
  test/env/env.go
  test/integration/ha.go
Labels: enhancement

#45 Fix conflict in k8s dependencies
  go.mod
  go.sum
Labels: bug

#39 Support multiport onit debug
  pkg/onit/cli/debug.go
  pkg/onit/common.go
  pkg/onit/util.go
Labels: enhancement

#48 Fix segfaults for device-presets and store-presets
  pkg/onit/cli/config.go
Labels: bug, enhancement

#47 Onit run test fails if the test does not exist
  pkg/onit/cli/run.go
Labels: enhancement

#49 Add --image-tags flag to support custom tags in Docker images
  pkg/onit/atomix.go
  pkg/onit/cli/create.go
  pkg/onit/cluster.go
  pkg/onit/common.go
  pkg/onit/config.go
  pkg/onit/network.go
  pkg/onit/onos-config.go
  pkg/onit/onos-topo.go
  pkg/onit/partitions.go
  pkg/onit/simulator.go
  pkg/onit/test.go
Labels: enhancement

#52 Add an example to show the usage of --image-tags option for creating …
  pkg/onit/cli/create.go
Labels: enhancement

#62 Add onos-cli deployment to onit cluster
  pkg/onit/cli/create.go
  pkg/onit/cluster.go
  pkg/onit/onos-cli.go
Labels: enhancement

#65 create docs directory to move onit docs to its own repo
  README.md
  docs/testing.md
Labels: documentation

#63 Add ssh capability to onit
  go.mod
  pkg/onit/cli/cli.go
  pkg/onit/cli/completion.go
  pkg/onit/cli/get.go
  pkg/onit/cli/ssh.go
  pkg/onit/common.go
  pkg/onit/onos-cli.go
Labels: enhancement

#67 Update and organize docs for onit
  README.md
  docs/run.md
  docs/setup.md
  docs/testing.md
Labels: documentation

#69 add stratum modelplugin when loading onos-config
  pkg/onit/onos-config.go
Labels: enhancement

#72 Fix a bug in onos-config to use correct modelplugins
  pkg/onit/onos-config.go
Labels: DO_NOT_MERGE

#75 Refactoring onit to implement local cluster
  pkg/onit/cli/add.go
  pkg/onit/cli/config.go
  pkg/onit/cli/create.go
  pkg/onit/cli/debug.go
  pkg/onit/cli/delete.go
  pkg/onit/cli/fetch.go
  pkg/onit/cli/get.go
  pkg/onit/cli/remove.go
  pkg/onit/cli/run.go
  pkg/onit/cli/set.go
  pkg/onit/cli/ssh.go
  pkg/onit/controller/interfaces.go
  pkg/onit/k8s/app.go
  pkg/onit/k8s/atomix.go
  pkg/onit/k8s/client.go
  pkg/onit/k8s/cluster.go
  pkg/onit/k8s/common.go
  pkg/onit/k8s/config.go
  pkg/onit/k8s/controller.go
  pkg/onit/k8s/gui.go
  pkg/onit/k8s/ingress.go
  pkg/onit/k8s/network.go
  pkg/onit/k8s/onos-cli.go
  pkg/onit/k8s/onos-config.go
  pkg/onit/k8s/onos-topo.go
  pkg/onit/k8s/output.go
  pkg/onit/k8s/partitions.go
  pkg/onit/k8s/simulator.go
  pkg/onit/k8s/test.go
  pkg/onit/k8s/util.go
  pkg/onit/local/cluster.go
Labels: enhancement

#81 Ensure app service correctly matches pods
  pkg/onit/k8s/app.go
Labels: bug

#95 Implement Set image command to redeploy a deployment with a new image
  docs/run.md
  pkg/onit/cli/set.go
  pkg/onit/k8s/image.go
Labels: enhancement
