Repository onosproject/onos-test, pull requests merged in 2020-03, with the labels that each got.

#257 Add a flag for maximum allowable mean latency on a benchmark
  pkg/benchmark/benchmark.go
  pkg/benchmark/benchmark.pb.go
  pkg/benchmark/benchmark.proto
  pkg/benchmark/cli.go
  pkg/benchmark/config.go
  pkg/benchmark/coordinator.go
  pkg/benchmark/worker.go
  pkg/onit/cli/benchmark.go
Labels: enhancement

#262 Rename onit env RAN functions to RIC
  pkg/onit/cli/create.go
  pkg/onit/cluster/cluster.go
  pkg/onit/cluster/ran.go
  pkg/onit/env/env.go
  pkg/onit/env/ric.go
  pkg/onit/setup/ric.go
  pkg/onit/setup/setup.go
Labels: DO_NOT_MERGE

#266 Added in call to create a Role and RoleBinding for the simulator
  pkg/benchmark/coordinator.go
  pkg/cluster/cluster.go
  pkg/cluster/runner.go
  pkg/onit/cluster/simulator.go
  pkg/util/logging/logging.go
Labels: bug
